# .github/workflows/release.yml
name: Release app

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    environment: release
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - { name: "windows", image: "windows-latest" }
          - { name: "linux", image: "ubuntu-22.04" }
    runs-on: ${{ matrix.os.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Publish App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: npm run publish

      - name: Find Build Output Path
        id: find_output
        shell: bash
        run: |
          if [[ "${{ matrix.os.name }}" == "windows" ]]; then
            OUTPUT_DIR="out/trio-win32-x64"
          else
            OUTPUT_DIR="out/trio-linux-x64"
          fi

          if [ ! -d "$OUTPUT_DIR" ]; then
            echo "Expected output directory '$OUTPUT_DIR' not found."
            ls -R out || true
            exit 1
          fi

          echo "Detected output directory: $OUTPUT_DIR"
          echo "artifact_path=$OUTPUT_DIR" >> "$GITHUB_OUTPUT"

      - name: Upload App Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os.name }}-app
          path: ${{ steps.find_output.outputs.artifact_path }}/*
          retention-days: 7

      - name: Upload Windows Installer
        if: contains(matrix.os.name, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: out/make/squirrel.windows/x64/*.exe
          retention-days: 7

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all built artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: |
            ## Release Notes
            * Initial release of the application.
            * This release is **unsigned**.
            ## Downloads
            See attached artifacts.
          draft: false
          prerelease: false
          files: |
            artifacts/windows-app/**/*
            artifacts/windows-installer/*.exe
            artifacts/linux-app/**/*
