# .github/workflows/release.yml

permissions:
  contents: write # Needed for uploading artifacts and creating a release
  # id-token: write # No longer needed if Sigstore is removed
  # actions: write # Might be implicitly needed for some actions, but contents:write is primary for release

name: Release app
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build:
    environment: release
    strategy:
      matrix:
        os: [
          { name: "windows", image: "windows-latest" },
          { name: "linux", image: "ubuntu-22.04" }
        ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4.1.1

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Confirm Node and NPM version
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: |
          npm ci || npm install

      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # These Apple secrets are likely for macOS notarization/distribution,
          # keep them if your 'npm run publish' uses them for Apple builds.
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: npm run publish
        # IMPORTANT: After this step, you need to know the path to your built artifacts.
        # For example: 'dist/your-app-windows.exe' and 'dist/your-app-linux'.

      # =====================================================================
      # UPLOAD BUILT APPLICATIONS AS JOB ARTIFACTS
      # This makes them available for download from the workflow run summary.
      # =====================================================================
      - name: Upload Windows App Artifact
        if: contains(matrix.os.name, 'windows')
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: dist/your-app-windows.exe # <-- **CHANGE THIS PATH** to your actual Windows build output
          retention-days: 7

      - name: Upload Linux App Artifact
        if: contains(matrix.os.name, 'linux')
        uses: actions/upload-artifact@v4
        with:
          name: linux-app
          path: dist/your-app-linux # <-- **CHANGE THIS PATH** to your actual Linux build output
          retention-days: 7

  # =====================================================================
  # CREATE GITHUB RELEASE
  # This job depends on the 'build' job and runs only once.
  # =====================================================================
  release:
    name: Create GitHub Release
    needs: build # This job will run only after all 'build' jobs are successful
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating a release
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts # Downloads all artifacts into this directory

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is automatically provided by GitHub Actions
        with:
          tag_name: ${{ github.event.inputs.version }} # Uses the version input from workflow_dispatch
          name: Release ${{ github.event.inputs.version }}
          body: |
            ## Release Notes

            * Initial release of the application.
            * This release is **unsigned**.

            ## Downloads

            See attached artifacts.
          draft: false # Set to true to create a draft release
          prerelease: false # Set to true for pre-releases
          files: |
            artifacts/windows-app/*
            artifacts/linux-app/*
